### ISSUE TITLE
Unrecognizable Symbol in Encryption Bingo 

### ISSUE THREAD

**Issue by VFlyer** [Red-P-enguin/EncryptionBingo#1]
[(https://ktane.timwi.de/More/Logfile%20Analyzer.html#file=ea748d1c0b8558dfe74d465b6a0f60875ddd14f2;bomb=NE3DH9)]
![image](https://user-images.githubusercontent.com/35939457/67178779-d966b700-f388-11e9-9888-8f7932654c68.png)
This is not the letter K in the Lombrax Cubes manual

**Comment by redpenguiin** [comment]
a) thanks
b) please just use reddit next time my username is RedPenguiin
